### ISSUE TITLE
Mongo: namespace too long error

### ISSUE THREAD

**Issue by poojabansal** [Sanjo/meteor-jasmine#217]
I recently updated meteor from v1.0.3.2 to v1.1.0.2 and noticed the following error in .meteor/local/log/jasmine-client-integration.log:
```
MongoError: namespace name generated from index name "jasmine-client-integration.covers.files.$metadata._Resumable.resumableIdentifier_1_metadata._Resumable.resumableChunkNumber_1_length_1" is too long (127 byte max)
```
Since its related to the meteor-file-collection package, I also opened a bug there: https://github.com/vsivsi/meteor-file-collection/issues/55. Reading the insights provided by Vaughn, may be the issue is related to jasmine?

**Comment by Sanjo** [comment]
As stated in my comment https://github.com/vsivsi/meteor-file-collection/issues/55#issuecomment-106883991 it's not a problem specific to sanjo:jasmine. Let's track this issue in https://github.com/vsivsi/meteor-file-collection/issues/55.

**Comment by vsivsi** [comment]
As I stated in my comment on the other issue,  https://github.com/vsivsi/meteor-file-collection/issues/55#issuecomment-106912880 , this is not a bug in my package. The bug lies in whatever code is constructing a database name that exceeds 127 characters and then attempts to use it without checking that it is valid. That is not happening in any code that I control.

**Comment by vsivsi** [comment]
@Sanjo 

Can @poojabansal  work around this by providing a shorter database name to meteor-jasmine?  

The code here seems to indicate that `'jasmine-client-integration'` is a default name that can be overridden.   https://github.com/Sanjo/meteor-jasmine/blob/b17a85bb1894886e3904866f7525aa5d49098bff/src/client/integration/ClientIntegrationTestFramework.js#L21

**Comment by Sanjo** [comment]
@poojabansal Sorry, but I won't change the name of the client integration mode because the database name plays a minor part in the index name length and it.

You can fork vsivsi/meteor-file-collection (use it as local package) and add a shorter name for the index. I've linked the documentation in https://github.com/vsivsi/meteor-file-collection/issues/55#issuecomment-106883991.
